// ----------------------------------------------------------------------

export const dao = [
  'Lueilwitz and Sons DAO',
  'Gleichner, Mueller and Tromp DAO',
  'Nikolaus - Leuschke DAO',
  'Hegmann, Kreiger and Bayer DAO',
  'Grimes Inc DAO',
  'Durgan - Murazik DAO',
  'Altenwerth, Medhurst and Roberts DAO',
  'Raynor Group DAO',
  'Mraz, Donnelly and Collins DAO',
  'Padberg - Bailey DAO',
  'Heidenreich, Stokes and Parker DAO',
  'Pagac and Sons DAO',
  'Rempel, Hand and Herzog DAO',
  'Dare - Treutel DAO',
  'Kihn, Marquardt and Crist DAO',
  'Nolan - Kunde DAO',
  'Wuckert Inc DAO',
  'Dibbert Inc DAO',
  'Goyette and Sons DAO',
  'Feest Grou DAOp',
  'Bosco and Sons DAO',
  'Bartell - Kovacek DAO',
  'Schimmel - Raynor DAO',
  'Tremblay LLC DAO',
  'Hills - Mitchell DAO',
  'Rogahn LLC DAO',
  'Kuhn, Osinski and Morar DAO',
  'Schmitt Inc DAO',
  'Breitenberg - Rosenbaum DAO',
  "O'Keefe, Schneider and Mraz DAO",
  'Rohan, Langworth and Kling DAO',
  'Morar and Sons DAO',
  'Mraz LLC DAO',
  'Rowe, Parisian and Kub DAO',
  'Marquardt - Hane DAO',
  'Medhurst Group DAO',
  'Nikolaus - Lang DAO',
  'Effertz, Mohr and Olson DAO',
  'Anderson - Kris DAO',
  'Runolfsson Group DAO'
];
